# Auto deploy app to gh-pages

name: Auto Deployment to gh-pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Download our master branch
    steps:
    - uses: actions/checkout@master
    # Install dependency for react-script to run
    - run: |
        npm install
        npm run build
    # Run deployment command
    - name: Deploying the static website to gh-pages
      with:
        branch: gh-pages
        folder: build
      env:
        IS_DEPLOY: true
