# Auto deploy app to gh-pages

name: Auto Deployment to gh-pages

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download master branch
      uses: actions/checkout@v2
    - name: Install dependency for react-script to run
      run: npm install
    - name: Configure Git User
      run: |
        git config --global user.email "akimotojh@gmail.com"
        git config --global user.name "Tan Jun Hui"
        git config user.email
        git config user.name
    # Run deployment command
    - name: Deploying the static website to gh-pages
      run: npm run deploy
      env:
        IS_DEPLOY: true
